version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    # depends_on:
    #   - db

  order-service:
    build: ./order-service
    ports:
      - "8002:8000"
    # depends_on:
    #   - db

  api-gateway:
    image: nginx
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

#   db:
#     image: postgres
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PORT: 5432
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: user_db
#     ports:
#     - 5435:5432

# volumes:
#   postgres-data: