name: CI/CD Pipeline for ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to Amazon ECR for Microservice 1
      - name: Log in to Amazon ECR for Microservice 1
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build, tag, and push Docker image for Microservice 1
      - name: Build, tag, and push Docker image for Microservice 1
        run: |
          docker build -t microservice1 ./microservice1
          docker tag microservice1:latest ${{ secrets.ECR_REPO_URL_1 }}/microservice1-repo:latest
          docker push ${{ secrets.ECR_REPO_URL_1 }}/microservice1-repo:latest

      # Step 5: Log in to Amazon ECR for Microservice 2
      - name: Log in to Amazon ECR for Microservice 2
        uses: aws-actions/amazon-ecr-login@v1

      # Step 6: Build, tag, and push Docker image for Microservice 2
      - name: Build, tag, and push Docker image for Microservice 2
        run: |
          docker build -t microservice2 ./microservice2
          docker tag microservice2:latest ${{ secrets.ECR_REPO_URL_2 }}/microservice2-repo:latest
          docker push ${{ secrets.ECR_REPO_URL_2 }}/microservice2-repo:latest

      # Step 7: Update ECS Service for Microservice 1
      - name: Update ECS Service for Microservice 1
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_1_NAME }} --force-new-deployment

      # Step 8: Update ECS Service for Microservice 2
      - name: Update ECS Service for Microservice 2
        run: |
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_2_NAME }} --force-new-deployment
